name: 'Generate File Matrix'
description: 'Gets matrix based on files created'
author: 'd10sfan'
runs:
    using: 'node16'
    main: 'dist/index.js'
inputs:
  name:
    description: Name of the folder to search in
    required: true
outputs:
  matrix:
    description: Matrix
